### ISSUE TITLE
Implementar as questões do módulo 1

### ISSUE THREAD

**Issue by aledosreis** [aledosreis/Colcheius#19]
Implementar as questões do módulo para buscar dinamicamente de acordo com o módulo.

**Comment by aledosreis** [comment]
Finalizada a implementação dessa funcionalidade, onde ao finalizar é enviado os dados para a tela de resultados da questão.

**Comment by CayAlves** [comment]
@aledosreis 
Tem um erro no texto de uma questão.
Na pergunta "O que é rítmo?" a resposta correta está escrita como "Divisão ordenada do tempo, REPRESENTA por batidas", temos que corrigir para REPRESENTADA

**Comment by CayAlves** [comment]
@aledosreis 
Quanto a Propriedades do Som só temos uma questão, que é sobre o Timbre. Que tal adicionarmos mais algumas questões nesse Módulo 1? (Ví que você já havia sugerido mais algumas mesmo)

Quais são as 4 propriedades do som?

a) Ouvido, Cordas vocais, Vibração e Ritmo

b) Timbre, volume, Densidade e tempo

c) Vibrações, ondas, intensidade e velocidade

d) Timbre, Duração, Intensidade e Altura

R: d

//

O que é a propriedade de Duração de um som?

a) o quão alto é um som

b) propriedade do som ser curto ou longo

c) propriedade do som ser forte ou fraco

d) nenhuma das alternativas

R: b

//

Qual propriedade do som o faz ser Grave, Médio ou Agudo?

a) Altura

b) Timbre

c) Intensidade

d) Duração

R: a

//

O que é a propriedade de Intensidade de um som?

a) Propriedade de um som ser estridente ou inaudível

b) Propriedade do som ser fraco ou forte

c) Propriedade do som ser curto ou longo

d) Nenhuma das alternativas

R: b

//

Quais são os elementos mais importantes da música?

a) Intensidade, volume e timbre

b) Altura, velocidade e vibrato

c) Tempo, som e silêncio

d) Melodia, Harmonia e Ritmo

R: d

**Comment by aledosreis** [comment]
@CayAlves Corrigido o erro apontado, e adicionado as questões sugeridas.
Também adicionei uma pergunta a mais, para termos um total de 10 perguntas (talvez seja bom termos 10 perguntas por módulo, para manter um padrão).

**Comment by aledosreis** [comment]
@CayAlves Segue abaixo todas as perguntas do módulo:

1 - "O que é música?",
- "Arte de se expressar através dos sons"
- "Qualquer som produzido pela natureza"
- "Qualquer som que nosso ouvido reconhece"
- "Arte de ouvir e reconhecer origem dos sons"

2 - "Quais são os elementos mais importantes da música?"
- "Melodia, Harmonia e Ritmo"
- "Tempo, som e silêncio"
- "Intensidade, volume e timbre"
- "Altura, velocidade e vibrato"

3 - "Qual foi a primeira manifestação musical do homem?"
- "Ritmo"
- "Dança"
- "k-pop"
- "Som de animais"

4 -"O que é ritmo?"
- "Divisão ordenada do tempo, representada por batidas"
- "Combinação de sons que se encaixam perfeitamente"
- "O melhor amigo do músico"
- "Todos os sons que possuem tempo e silêncio"

5 - "O que é o metrônomo?"
- "Instrumento usado para marcar o andamento na música"
- "Nenhuma das alternativas"
- "Uma propriedade do som"
- "Aparelho usado para afinar instrumentos musicais"

6 - "Quais são as 4 propriedades do som?"
- "Timbre, Duração, Intensidade e Altura"
- "Vibrações, ondas, intensidade e velocidade"
- "Timbre, volume, Densidade e tempo"
- "Ouvido, Cordas vocais, Vibração e Ritmo"

7 - "Entre as propriedades do som, qual das seguintes nos permite reconhecer a origem do som?"
- "Timbre"
- "Melodia"
- "Altura"
- "Intensidade"

8 - "O que é a propriedade de Duração de um som?"
- "propriedade do som ser curto ou longo"
- "o quão alto é um som"
- "propriedade do som ser forte ou fraco"
- "nenhuma das alternativas"

9 - "Qual propriedade do som o faz ser Grave, Médio ou Agudo?"
- "Altura"
- "Timbre"
- "Intensidade"
- "Duração"

10 -  "O que é a propriedade de Intensidade de um som?"
- "Propriedade do som ser fraco ou forte"
- "Propriedade de um som ser estridente ou inaudível"
- "Propriedade do som ser curto ou longo"
- "Nenhuma das alternativas"

OBS: na aplicação as perguntas não aparecem na mesma ordem acima, sendo mostradas de forma aleatória, e o mesmo acontece com as respostas.
