### ISSUE TITLE
Teoria/Questões do Módulo 2

### ISSUE THREAD

**Issue by aledosreis** [aledosreis/Colcheius#22]
Criar e implementar a teoria e as questões referentes ao módulo 2, de acordo ao que foi definido em #5 (existe a possibilidade de alteração, caso necessário).

**Comment by CayAlves** [comment]
Teoria MÓDULO 2

FIGURAS

As diferentes durações de sons podem ser representados por Figuras, que são símbolos utilizados para representar os tempos de uma música, cada uma tem seu nome e também um número pelo qual é representada. Toda figura de som tem sua respectiva figura de silêncio, assim como na imagem abaixo:
(img 1)

//

Seguindo a ordem das figuras na vista na tabela anterior, podemos perceber que conforme avançamos (descendo a partir da Semibreve), as figuras valem a metade de sua anterior, assim como quando fazemos o processo contrário (subindo a partir da Semifusa) as figuras seguintes valem o dobro de sua anterior. Isso pode ser melhor representado da seguinte forma:
(img 2)

Podemos concluir que 2 Mínimas tem o mesmo valor que 1 Semibreve, 2 Semínimas tem o mesmo valor que 1 Mínima e assim por diante, também como 32 Fusas equivalem a 1 Semibreve.

Pode-se notar na imagem anterior que algumas figuras podem aparecer ligadas por uma barra de união:
Duas colcheias, uma ao lado da outra (img 3) ao serem ligadas formam (img 3.1)

//

GRAVES E AGUDOS

Altura do som é um termo utilizado para definir se um som é agudo ou grave. Sons altos são agudos e sons baixos são graves. O que faz um som ficar agudo ou grave é a frequência do som. Quanto maior a frequência, mais agudo (alto) é o som; e quanto menor a frequência, mais grave (baixo) é o som. Essa frequência corresponde aos ciclos (oscilações por segundo) da onda sonora. Assim como abordado no módulo anterior, se executarmos as teclas de um piano da esquerda para a direita, percebemos que o som começa grave e vai se tornando mais agudo conforme caminhamos pelas teclas até o lado oposto.
Obs: É importante não confundir altura do som com volume (ou intensidade) do som. A intensidade faz o som ser fraco ou forte, independente dele ser grave ou agudo.

//

Exercícios MÓDULO 2

1- O que são figuras musicais?

a) É o contorno que uma partitura

b) São sinais gráficos que representam diferentes durações de sons, sendo mais curtos ou mais longos.

c) São traços que dividem as notas em um sistema musical

d) São sinais que indicam diferentes timbres na música

//

2- Qual figura tem a maior duração?

a) Mínima

b) Colcheia

c) Fusa

d) Semibreve

//

3- Qual das alternativas abaixo contém a figura de MAIOR duração entre elas?

a) Colcheia

b) Semifusa

c) Semínima

d) Semicolcheia

//

4- Qual das alternativas abaixo contém a figura de MENOR duração entre elas?

a) Semicolcheia

b) Semibreve

c) Colcheia

d) Mínima

//

5- Quantas Mínimas seriam necessárias para representar o mesmo valor de 1 Semibreve?

a) 4

b) 2

c) 6

d) Nenhuma das alternativas anteriores.

//

6- A Colcheia é representada por qual número?

a) 2

b) 1

c) 4

d) 8

//

7- A Semínima é representada por qual número?

a) 4

b) 6

c) 8

d) 16

//

8- Qual propriedade do som permite um som ser grave ou agudo?

a) Timbre

b) Duração

c) Intensidade

d) Altura

//

9- O que faz um som ser agudo?

a) Uma baixa frequência de ondas sonoras

b) A capacidade de alguém gritar fino

c) Uma alta frequência de ondas sonoras

d) Um falsete de um cantor

//

10- Uma baixa frequência de ondas sonoras é considerado um som:

a) Agudo

b) Fraco

c) Irritante

d) Grave



@aledosreis se achar necessário a gente pode acrescentar, excluir ou alterar algumas questões

**Comment by aledosreis** [comment]
Implementado a teoria do módulo 2

**Comment by aledosreis** [comment]
@CayAlves implementei 4 questões do módulo apenas para padronizar com relação ao anterior, as demais ficam para futuramente colocarmos mais questões.

**Comment by CayAlves** [comment]
@aledosreis 
Na questão "Quantas mínimas seriam necessárias para representar o mesmo valor de 1 Semibreve?"
A alternativa "Nenhuma das alternativas anteriores" não aparece por ultimo, melhor seria retirarmos a palavra "anteriores"

**Comment by CayAlves** [comment]
@aledosreis 
Na primeira tela de teoria das Figuras, acho melhor adicionar mais um texto pequeno deixando claro que a Semibreve é a figura de maior duração e a semifusa a de menor duração. 
Acho que isso precisa ficar mais claro pra não haver dúvida no usuário

Sugestão: "Vale notar que a Semibreve é a figura de maior duração, enquanto a semifusa é a de menor duração"

**Comment by aledosreis** [comment]
@CayAlves Realizada a alteração sugerida nas questões e na teoria do módulo.

Também adicionei o restante das perguntas do módulo 2 conforme anteriormente sugerido, tendo agora um total de 10 perguntas.
Seguem as Questões do módulo

1- O que são figuras musicais?
a) É o contorno que envolve uma partitura
b) São símbolos que representam diferentes durações de sons, sendo mais curtos ou mais longos.
c) São traços que dividem as notas em um sistema musical
d) São sinais que indicam diferentes timbres na música

2- Qual figura tem a maior duração?
a) Mínima
b) Colcheia
c) Fusa
d) Semibreve

3- Qual das alternativas abaixo contém a figura de MAIOR duração entre elas?
a) Colcheia
b) Semifusa
c) Semínima
d) Semicolcheia

4- Qual das alternativas abaixo contém a figura de MENOR duração entre elas?
a) Semicolcheia
b) Semibreve
c) Colcheia
d) Mínima

5- Quantas Mínimas seriam necessárias para representar o mesmo valor de 1 Semibreve?
a) 4
b) 2
c) 6
d) Nenhuma das alternativas.

6- A Colcheia é representada por qual número?
a) 2
b) 1
c) 4
d) 8

7- A Semínima é representada por qual número?
a) 4
b) 6
c) 8
d) 16

8- Qual propriedade do som permite um som ser grave ou agudo?
a) Timbre
b) Duração
c) Intensidade
d) Altura

9- O que faz um som ser agudo?
a) Uma baixa frequência de ondas sonoras
b) A capacidade de alguém gritar fino
c) Uma alta frequência de ondas sonoras
d) Um falsete de um cantor

10- Uma baixa frequência de ondas sonoras é considerado um som:
a) Agudo
b) Fraco
c) Irritante
d) Grave
