### ISSUE TITLE
Teoria / Questões do módulo 3

### ISSUE THREAD

**Issue by aledosreis** [aledosreis/Colcheius#23]
Criar e implementar a teoria e as questões referentes ao módulo 3, de acordo ao que foi definido em #5 (existe a possibilidade de alteração, caso necessário).

**Comment by CayAlves** [comment]
MÓDULO 3 

Compasso

Já sabemos que para determinar o ritmo e a duração das figuras, utilizamos o tempo (relógio/metrônomo) como medida.
O compasso nada mais é que uma forma de agrupar tempos, que podem ser agrupados de 2 em 2 (compasso binário), de 3 em 3 (compasso ternário), de 4 em 4 (compasso quaternário), etc.
Esses compassos podem ser simples ou compostos.

//

Barras de Compasso

Para representarmos os compassos na música utilizamos barras de compasso (ou barra simples)
(aqui vai Img1)
Como visto, o espaço que há entre duas barras é o que chamamos de compasso.

//

Para concluir (finalizar) uma partitura, utilizamos a barra final.
(aqui vai Img2)

E para separar certos trechos da música (como separar verso de refrão) utilizamos a barra dupla.
(aqui vai Img3)

//

Ritornello

O Ritornello serve para indicar uma repetição de certo trecho na música, ou seja, tudo o que estiver entre dois sinais de Ritornello deverá ser tocado novamente. 
Exemplo:
(aqui vai Img4)
Logo após repetir o trecho, continua-se tocando os compassos seguintes normalmente.

//

EXERCÍCIOS

1- O que é um compasso?

a) É um instrumento usado para desenhar formas redondas

b) É o agrupamento de tempos

c) Separação de versos

d) O espaço entre figuras musicais

//

2- "O compasso que agrupa 4 tempos é o ________; o que agrupa 2 tempos é o ______; e o que agrupa 3 tempos é o ______."
Qual das alternativas abaixo completam, respectivamente, a afirmação acima?
 
a) Quaternário; duplo; ternário

b) Quádruplo; binário; terciário 

c) Quaternário; binário; ternário

d) Quadrante; bípede; terceiro

//

3- O que separa compassos numa partitura é uma linha vertical, chamada: 
 
a) Ritornello

b) Barra de compasso

c) Barra dupla

d) Linha de compasso

//

4- Pra que serve uma Barra final?

a) Para indicar o fim de uma nota

b) Para mostrar onde respiramos na música

c) Indica separação entre verso e refrão

d) Para indicar a conclusão ou finalização de uma partitura

//

5- Para que servem os Sinais de Ritornello?

a) Para retornar ao início de uma partitura

b) Para repetir o que há entre dois sinais de Ritornello

c) É onde vamos reiniciar a execução de uma música

d) Significa importância do compasso que está entre dois sinais de Ritornello


[Nesse módulo também íamos abordar fórmula de compasso, mas acho que ficaria extenso demais, é uma parte que devemos dar mais atenção só pra ela. Por isso acho melhor jogar para o próximo módulo]

**Comment by aledosreis** [comment]
@CayAlves Foi adicionada as questões referentes ao módulo 3. Creio que nesse caso por termos deixado fórmula de compasso simples (e consequentemente a parte de acentuação métrica) para o módulo posterior, seria dificil termos as 10 questões como nos módulos anteriores. Acho que as que já temos estão boas, mas caso a gente tenha mais ideias adicionamos depois.

Vou seguir agora com a implementação da teoria.

**Comment by aledosreis** [comment]
Implementado a teoria do módulo 3.
